version: '2.2'
services:
    fullanaysis:
        container_name: full
        build: FullAnalysis
        ports:
            - 8050:8050
            - 6000-6010:6000-6010
        env_file:
            - ./FullAnalysis/.env    
        volumes:
            - './DATA/OUTPUTS:/app/OUTPUTS'