FROM python:latest


RUN pip install -U spacy

COPY . /app
WORKDIR /app
RUN python -m spacy download en_core_web_sm

# Run the specified command within the container.
CMD [ "python", "KeywordExtracter.py"]
