FROM python:latest as base
FROM base as builder
RUN mkdir /install
WORKDIR /install
COPY requirements.txt /requirements.txt
RUN pip install -U --no-cache-dir --prefix="/install" -r /requirements.txt
FROM base
EXPOSE 8050
EXPOSE 6000-6010
#bring basic tools across
COPY --from=builder /install /usr/local
RUN python -m spacy download en_core_web_sm


WORKDIR /app
COPY __init__.py .
RUN python __init__.py
COPY ./APPS ./APPS
COPY ./UTILS ./UTILS
COPY App.py .


# Run the specified command within the container.
CMD [ "python", "App.py"]
