FROM python:latest as base
FROM base as builder
RUN mkdir /install
WORKDIR /install
COPY requirements.txt /requirements.txt
RUN pip install -U --no-cache-dir --prefix="/install" -r /requirements.txt
FROM base

#bring basic tools across
COPY --from=builder /install /usr/local
RUN python -m spacy download en_core_web_sm

COPY setup.py .
RUN python setup.py
COPY ./DATA /app/DATA
COPY Full.py /app
WORKDIR /app

# Run the specified command within the container.
CMD [ "python", "Full.py"]
